"use client";
import React, { useEffect, useState } from "react";
import Link from "next/link";

type StyleResultData = {
    id: string;
    styles: string[];
    recommended_colors: string[];
    summary: string;
    analysis: {
        skin_tone?: string;
        hair_color?: string;
        body_type?: string;
        overall_aesthetic?: string;
    };
    created_at: string;
};

const COLOR_MAP: Record<string, string> = {
    black: "#1A1A1A",
    white: "#FFFFFF",
    navy: "#1B2A4A",
    red: "#C0392B",
    green: "#27AE60",
    beige: "#D4C5A9",
    grey: "#9E9E9E",
    brown: "#795548",
    olive: "#808000",
    burgundy: "#800020",
    camel: "#C19A6B",
    cream: "#FFFDD0",
};

export default function AIStyleResult({ id }: { id: string }) {
    const [data, setData] = useState<StyleResultData | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        fetch(`/api/share-style?id=${id}`)
            .then(res => res.json())
            .then(json => {
                if (json.success) setData(json.data);
                else setError("This style result could not be found.");
            })
            .catch(() => setError("Failed to load style result."))
            .finally(() => setLoading(false));
    }, [id]);

    if (loading) {
        return (
            <main style={{ background: "#F6F5F2", minHeight: "100vh" }}>
                <section className="flex flex-col items-center justify-center text-center pt-[120px] pb-20">
                    <div className="animate-spin rounded-full h-8 w-8" style={{ borderWidth: "2px", borderStyle: "solid", borderColor: "transparent", borderTopColor: "#0A0A0A" }} />
                    <p className="text-xs font-light mt-4 animate-pulse" style={{ color: "#8A8A8A" }}>Loading style result…</p>
                </section>
            </main>
        );
    }

    if (error || !data) {
        return (
            <main style={{ background: "#F6F5F2", minHeight: "100vh" }}>
                <section className="flex flex-col items-center justify-center text-center pt-[120px] pb-20 px-4">
                    <h1 className="font-playfair text-3xl font-normal text-dark mb-4">Result Not Found</h1>
                    <p className="text-sm font-light mb-8" style={{ color: "#8A8A8A" }}>
                        {error || "This style result is no longer available."}
                    </p>
                    <Link
                        href="/ai-style-from-photo"
                        className="py-3 px-8 text-xs font-light tracking-[0.15em] uppercase"
                        style={{ background: "#0A0A0A", color: "#F6F5F2" }}
                    >
                        Try AI Style From Photo
                    </Link>
                </section>
            </main>
        );
    }

    return (
        <main style={{ background: "#F6F5F2" }}>
            {/* Hero */}
            <section
                className="flex flex-col items-center justify-center text-center pt-[120px] lg:pt-[160px] pb-16 px-4"
                style={{ background: "#0A0A0A" }}
            >
                <span className="block text-xs font-light tracking-[0.35em] uppercase mb-6" style={{ color: "rgba(246,245,242,0.45)" }}>
                    AI Style Profile
                </span>
                <h1 className="font-playfair text-4xl md:text-5xl font-normal mb-4" style={{ color: "#F6F5F2", letterSpacing: "-0.03em" }}>
                    A Personalized Look
                </h1>
                <p className="font-light text-sm max-w-sm leading-relaxed" style={{ color: "rgba(246,245,242,0.5)" }}>
                    This style profile was generated by FITOVA AI based on a personal photo analysis.
                </p>
            </section>

            {/* Content */}
            <section className="py-16">
                <div className="max-w-[700px] mx-auto px-4 sm:px-8 xl:px-0 space-y-10">

                    {/* Profile Summary */}
                    <div className="p-6" style={{ background: "#FFFFFF", border: "1px solid #E8E4DF" }}>
                        <p className="text-[10px] font-light tracking-[0.1em] uppercase mb-3" style={{ color: "#8A8A8A" }}>Style Analysis</p>
                        <p className="text-sm font-light leading-relaxed" style={{ color: "#4A4A4A" }}>{data.summary}</p>
                        <div className="flex flex-wrap gap-2 mt-4">
                            {[
                                data.analysis?.skin_tone,
                                data.analysis?.body_type,
                                data.analysis?.overall_aesthetic,
                            ].filter(Boolean).map((tag, i) => (
                                <span key={i} className="text-[10px] uppercase tracking-wider py-1 px-3" style={{ background: "#F6F5F2", color: "#4A4A4A" }}>
                                    {tag}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* Detected Styles */}
                    <div>
                        <h2 className="font-playfair text-xl font-normal text-dark mb-4" style={{ letterSpacing: "-0.02em" }}>Detected Styles</h2>
                        <div className="flex flex-wrap gap-2">
                            {data.styles.map(style => (
                                <Link
                                    key={style}
                                    href={`/outfits?style=${style.toLowerCase()}`}
                                    className="px-5 py-2.5 text-xs font-light tracking-[0.15em] uppercase"
                                    style={{ background: "#0A0A0A", color: "#F6F5F2" }}
                                >
                                    {style}
                                </Link>
                            ))}
                        </div>
                    </div>

                    {/* Color Palette */}
                    <div>
                        <h2 className="font-playfair text-xl font-normal text-dark mb-4" style={{ letterSpacing: "-0.02em" }}>Recommended Colors</h2>
                        <div className="flex flex-wrap gap-4">
                            {data.recommended_colors.map(color => {
                                const hex = COLOR_MAP[color.toLowerCase()] || "#CCCCCC";
                                const isLight = ["white", "cream", "beige"].includes(color.toLowerCase());
                                return (
                                    <div key={color} className="flex flex-col items-center gap-2">
                                        <div
                                            className="w-10 h-10 rounded-full border"
                                            style={{ background: hex, borderColor: isLight ? "#E8E4DF" : hex }}
                                        />
                                        <span className="text-[10px] tracking-wider uppercase" style={{ color: "#8A8A8A" }}>
                                            {color}
                                        </span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    {/* CTA */}
                    <div className="text-center py-8 px-6" style={{ background: "#0A0A0A" }}>
                        <p className="font-playfair text-xl font-normal mb-2" style={{ color: "#F6F5F2" }}>
                            Get Your Own AI Style Profile
                        </p>
                        <p className="text-xs font-light mb-6" style={{ color: "rgba(246,245,242,0.5)" }}>
                            Upload your photo and discover what styles were made for you.
                        </p>
                        <Link
                            href="/ai-style-from-photo"
                            className="inline-block py-3 px-8 text-xs font-light tracking-[0.15em] uppercase transition-all duration-200"
                            style={{ background: "#F6F5F2", color: "#0A0A0A" }}
                        >
                            Try It Yourself →
                        </Link>
                    </div>

                </div>
            </section>
        </main>
    );
}
