"use client";
import React, { useEffect, useState } from "react";
import Link from "next/link";

type MirrorResult = {
    id: string;
    original_image_url: string;
    ai_image_url: string;
    styles: string[];
    colors: string[];
    summary: string;
    analysis_json: {
        gender?: string;
        skin_tone?: string;
        face_shape?: string;
        body_type?: string;
    };
    clothing_suggestions: {
        tops?: string[];
        bottoms?: string[];
        shoes?: string[];
    };
    created_at: string;
};

const COLOR_HEX: Record<string, string> = {
    black: "#1A1A1A", white: "#FFFFFF", navy: "#1B2A4A", red: "#C0392B",
    green: "#27AE60", beige: "#D4C5A9", grey: "#9E9E9E", brown: "#795548",
    olive: "#808000", burgundy: "#800020", camel: "#C19A6B", cream: "#FFFDD0",
    blue: "#2980B9", pink: "#E91E8C", orange: "#E67E22",
};

export default function MirrorStyleShare({ token }: { token: string }) {
    const [data, setData] = useState<MirrorResult | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        fetch(`/api/mirror-style/share/${token}`)
            .then(res => res.json())
            .then(json => {
                if (json.success) setData(json.data);
                else setError("This style profile could not be found.");
            })
            .catch(() => setError("Failed to load style profile."))
            .finally(() => setLoading(false));
    }, [token]);

    if (loading) {
        return (
            <main style={{ background: "#F6F5F2", minHeight: "100vh" }}>
                <section className="flex flex-col items-center justify-center text-center pt-[140px] pb-20">
                    <div className="animate-spin rounded-full h-7 w-7 mb-4" style={{ borderWidth: "1.5px", borderStyle: "solid", borderColor: "transparent", borderTopColor: "#0A0A0A" }} />
                    <p className="text-xs font-light text-[#8A8A8A] animate-pulse tracking-[0.1em]">Loading style profile…</p>
                </section>
            </main>
        );
    }

    if (error || !data) {
        return (
            <main style={{ background: "#F6F5F2", minHeight: "100vh" }}>
                <section className="flex flex-col items-center justify-center text-center pt-[140px] pb-20 px-4">
                    <h1 className="font-playfair text-3xl font-normal text-[#0A0A0A] mb-3">Not Found</h1>
                    <p className="text-sm font-light text-[#8A8A8A] mb-8">{error}</p>
                    <Link href="/mirror-style" className="py-3 px-8 text-xs font-light tracking-[0.15em] uppercase bg-[#0A0A0A] text-white">
                        Try Mirror Style
                    </Link>
                </section>
            </main>
        );
    }

    const hasImages = data.original_image_url || data.ai_image_url;

    return (
        <main style={{ background: "#F6F5F2" }}>
            {/* Hero */}
            <section className="flex flex-col items-center text-center pt-[120px] lg:pt-[160px] pb-16 px-4" style={{ background: "#0A0A0A" }}>
                <span className="text-xs font-light tracking-[0.3em] uppercase mb-5" style={{ color: "rgba(246,245,242,0.4)" }}>Mirror Style ✦ AI Profile</span>
                <h1 className="font-playfair text-4xl md:text-5xl font-normal mb-3" style={{ color: "#F6F5F2", letterSpacing: "-0.03em" }}>
                    Style Transformation
                </h1>
                <p className="text-xs font-light max-w-sm" style={{ color: "rgba(246,245,242,0.45)", lineHeight: 2 }}>
                    AI-powered fashion profile generated by FITOVA Mirror Style
                </p>
            </section>

            <section className="py-16">
                <div className="max-w-[800px] mx-auto px-4 sm:px-8 xl:px-0 space-y-8">

                    {/* Before / After Images */}
                    {hasImages && (
                        <div>
                            <p className="text-[10px] font-medium tracking-[0.25em] uppercase text-[#8A8A8A] mb-4">Before — After</p>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                                {data.original_image_url && (
                                    <div className="relative">
                                        <div className="absolute top-3 left-3 z-10">
                                            <span className="px-3 py-1 text-[10px] tracking-[0.15em] uppercase font-light" style={{ background: "rgba(10,10,10,0.7)", color: "#F6F5F2" }}>Before</span>
                                        </div>
                                        <img src={data.original_image_url} alt="Original" className="w-full aspect-[3/4] object-cover object-top" style={{ border: "1px solid #E8E4DF" }} />
                                    </div>
                                )}
                                {data.ai_image_url ? (
                                    <div className="relative">
                                        <div className="absolute top-3 left-3 z-10">
                                            <span className="px-3 py-1 text-[10px] tracking-[0.15em] uppercase font-light" style={{ background: "rgba(10,10,10,0.7)", color: "#F6F5F2" }}>AI Styled</span>
                                        </div>
                                        <img src={data.ai_image_url} alt="AI styled" className="w-full aspect-[3/4] object-cover object-top" style={{ border: "1px solid #E8E4DF" }} />
                                    </div>
                                ) : (
                                    data.original_image_url && (
                                        <div className="w-full aspect-[3/4] flex items-center justify-center" style={{ background: "#F0EDE8", border: "1px solid #E8E4DF" }}>
                                            <p className="text-xs font-light text-center text-[#8A8A8A] px-4">Style recommendations below</p>
                                        </div>
                                    )
                                )}
                            </div>
                        </div>
                    )}

                    {/* Style profile summary */}
                    <div className="p-6 bg-white" style={{ border: "1px solid #0A0A0A" }}>
                        <p className="text-[10px] font-medium tracking-[0.25em] uppercase text-[#8A8A8A] mb-3">YourStyle Profile</p>
                        <p className="text-sm font-light leading-relaxed text-[#4A4A4A]">{data.summary}</p>
                        <div className="flex flex-wrap gap-2 mt-4">
                            {[data.analysis_json?.skin_tone, data.analysis_json?.body_type, data.analysis_json?.face_shape]
                                .filter(Boolean).map((tag, i) => (
                                    <span key={i} className="text-[10px] uppercase tracking-wider py-1 px-3 bg-[#F6F5F2] text-[#4A4A4A]">{tag}</span>
                                ))}
                        </div>
                    </div>

                    {/* Styles */}
                    <div>
                        <p className="text-[10px] font-medium tracking-[0.25em] uppercase text-[#8A8A8A] mb-4">Detected Styles</p>
                        <div className="flex flex-wrap gap-3">
                            {data.styles.map(style => (
                                <Link
                                    key={style}
                                    href={`/outfits?style=${style}`}
                                    className="px-6 py-3 text-xs font-light tracking-[0.18em] uppercase bg-[#0A0A0A] text-white hover:bg-[#2C2C2C] transition-colors duration-200"
                                >
                                    {style}
                                </Link>
                            ))}
                        </div>
                    </div>

                    {/* Colors */}
                    <div className="p-6 bg-white" style={{ border: "1px solid #E8E4DF" }}>
                        <p className="text-[10px] font-medium tracking-[0.25em] uppercase text-[#8A8A8A] mb-5">Recommended Colors</p>
                        <div className="flex flex-wrap gap-5">
                            {data.colors.map(color => {
                                const hex = COLOR_HEX[color.toLowerCase()] || "#CCCCCC";
                                const isLight = ["white", "cream", "beige"].includes(color.toLowerCase());
                                return (
                                    <div key={color} className="flex flex-col items-center gap-2">
                                        <div
                                            className="w-10 h-10 rounded-full"
                                            style={{ background: hex, border: `2px solid ${isLight ? "#E8E4DF" : hex}`, boxShadow: "0 2px 8px rgba(0,0,0,0.1)" }}
                                        />
                                        <span className="text-[10px] tracking-wider uppercase text-[#8A8A8A]">{color}</span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    {/* CTA */}
                    <div className="text-center py-10 px-6" style={{ background: "#0A0A0A" }}>
                        <p className="font-playfair text-2xl font-normal mb-2" style={{ color: "#F6F5F2" }}>
                            Get Your Own Mirror Style
                        </p>
                        <p className="text-xs font-light mb-6" style={{ color: "rgba(246,245,242,0.45)", lineHeight: 2 }}>
                            Upload your photo and let AI discover the styles, colors, and outfits made for you.
                        </p>
                        <div className="flex flex-col sm:flex-row gap-3 justify-center items-center">
                            <Link
                                href="/mirror-style"
                                className="inline-block py-3.5 px-8 text-xs font-light tracking-[0.15em] uppercase transition-all duration-200 hover:opacity-80"
                                style={{ background: "#F6F5F2", color: "#0A0A0A" }}
                            >
                                Try Mirror Style →
                            </Link>
                            <Link
                                href="/signup"
                                className="inline-block py-3.5 px-8 text-xs font-light tracking-[0.15em] uppercase border border-[rgba(246,245,242,0.3)] text-[rgba(246,245,242,0.7)] hover:border-[rgba(246,245,242,0.6)] transition-all duration-200"
                            >
                                Create Account
                            </Link>
                        </div>
                    </div>
                </div>
            </section>
        </main>
    );
}
