import type { Metadata } from "next";
import MirrorStyleShare from "@/components/MirrorStyleShare";

export const metadata: Metadata = {
    title: "Mirror Style — Shared Look | FITOVA",
    description: "See a personalized AI fashion profile — styles, colors, and a styled look generated by FITOVA Mirror Style.",
};

interface PageProps {
    params: Promise<{ token: string }>;
}

export default async function MirrorStyleSharePage({ params }: PageProps) {
    const { token } = await params;
    return <MirrorStyleShare token={token} />;
}
