"use client";
import React from "react";
import StatsCard from "@/components/Admin/StatsCard";
import { useQuery } from "@tanstack/react-query";
import { adminService } from "@/services/admin.service";
import {
    LineChart, Line, BarChart, Bar, AreaChart, Area, PieChart, Pie, Cell,
    XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend
} from "recharts";

const COLORS = ['#8B7355', '#4A6FA5', '#5C8A6A', '#A55C4A', '#6B5B8A', '#0A0A0A'];

export default function AdminAnalyticsPage() {
    const { data: analytics, isLoading, error } = useQuery({
        queryKey: ["admin-detailed-analytics"],
        queryFn: adminService.getDetailedAnalytics,
        refetchInterval: 60000 // Refresh every minute
    });

    if (error) {
        return <div className="p-8 text-red-500">Error loading analytics: {(error as any).message}</div>;
    }

    const counts = analytics?.counts || {
        products: 0, categories: 0, collections: 0, offers: 0, users: 0,
        reviews: 0, wishlist: 0, newsletters: 0, contacts: 0, styleWorlds: 0
    };
    const charts = analytics?.charts || { signups: [], topWishlist: [], offersPerformance: [], styleHubColors: [] };

    // Common tooltip style for recharts
    const tooltipStyle = { backgroundColor: '#fff', border: '1px solid #E8E4DF', borderRadius: '4px', fontSize: '12px' };

    return (
        <div className="space-y-8">
            {/* Header */}
            <div>
                <span className="text-xs font-light tracking-[0.3em] uppercase text-[#8A8A8A]">Intelligence</span>
                <h2 className="font-playfair font-normal text-3xl text-[#0A0A0A] mt-1" style={{ letterSpacing: "-0.02em" }}>
                    Comprehensive Analytics
                </h2>
                <p className="text-sm font-light text-[#8A8A8A] mt-2">Real-time metrics aggregating all platform activity.</p>
            </div>

            {/* Dense Stats Grid */}
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
                <StatsCard title="Total Users" value={isLoading ? "..." : counts.users} description="Registered Accounts" color="#4A6FA5" icon={<span />} />
                <StatsCard title="Total Products" value={isLoading ? "..." : counts.products} description="Active Catalog" color="#8B7355" icon={<span />} />
                <StatsCard title="Total Orders" value={isLoading ? "..." : 0} description="Order History (Mock)" color="#5C8A6A" icon={<span />} />
                <StatsCard title="Wishlist Saves" value={isLoading ? "..." : counts.wishlist} description="Products Favorited" color="#A55C4A" icon={<span />} />
                <StatsCard title="Style Worlds" value={isLoading ? "..." : counts.styleWorlds} description="Generated by AI" color="#6B5B8A" icon={<span />} />

                <StatsCard title="Newsletter Subs" value={isLoading ? "..." : counts.newsletters} description="Active Subscribers" color="#0A0A0A" icon={<span />} />
                <StatsCard title="Product Reviews" value={isLoading ? "..." : counts.reviews} description="Customer Feedback" color="#4A4A4A" icon={<span />} />
                <StatsCard title="Active Offers" value={isLoading ? "..." : counts.offers} description="Coupons & Promos" color="#8B7355" icon={<span />} />
                <StatsCard title="Contact Msgs" value={isLoading ? "..." : counts.contacts} description="Inbox Inquiries" color="#4A6FA5" icon={<span />} />
                <StatsCard title="Collections" value={isLoading ? "..." : counts.collections} description="Curated Lookbooks" color="#5C8A6A" icon={<span />} />
            </div>

            {/* Large Charts Row 1 */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* 1. Area Chart: User Growth */}
                <div className="bg-white border border-[#E8E4DF] p-6 shadow-sm rounded-sm">
                    <h3 className="text-sm font-medium text-[#0A0A0A] mb-1">User Growth & Signups</h3>
                    <p className="text-xs text-[#8A8A8A] mb-6 font-light">Daily account creations based on recent activity</p>
                    <div className="h-[300px] w-full">
                        {isLoading ? <div className="h-full flex items-center justify-center text-[#8A8A8A] text-sm">Loading...</div> : (
                            <ResponsiveContainer width="100%" height="100%">
                                <AreaChart data={charts.signups} margin={{ top: 5, right: 20, bottom: 5, left: -20 }}>
                                    <defs>
                                        <linearGradient id="colorSignups" x1="0" y1="0" x2="0" y2="1">
                                            <stop offset="5%" stopColor="#4A6FA5" stopOpacity={0.3} />
                                            <stop offset="95%" stopColor="#4A6FA5" stopOpacity={0} />
                                        </linearGradient>
                                    </defs>
                                    <CartesianGrid stroke="#f5f5f5" strokeDasharray="3 3" vertical={false} />
                                    <XAxis dataKey="date" tick={{ fill: '#8A8A8A', fontSize: 11 }} axisLine={false} tickLine={false} dy={10} minTickGap={20} />
                                    <YAxis tick={{ fill: '#8A8A8A', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} />
                                    <Tooltip contentStyle={tooltipStyle} cursor={{ stroke: '#f5f5f5', strokeWidth: 2 }} />
                                    <Area type="monotone" dataKey="signups" stroke="#4A6FA5" strokeWidth={2} fillOpacity={1} fill="url(#colorSignups)" />
                                </AreaChart>
                            </ResponsiveContainer>
                        )}
                    </div>
                </div>

                {/* 2. Bar Chart: Top Wishlisted Products */}
                <div className="bg-white border border-[#E8E4DF] p-6 shadow-sm rounded-sm">
                    <h3 className="text-sm font-medium text-[#0A0A0A] mb-1">Top Wishlisted Products</h3>
                    <p className="text-xs text-[#8A8A8A] mb-6 font-light">Most favorited items across all users</p>
                    <div className="h-[300px] w-full">
                        {isLoading ? <div className="h-full flex items-center justify-center text-[#8A8A8A] text-sm">Loading...</div> : (
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={charts.topWishlist} margin={{ top: 5, right: 20, bottom: 5, left: -10 }}>
                                    <CartesianGrid stroke="#f5f5f5" strokeDasharray="3 3" vertical={false} />
                                    <XAxis dataKey="name" tick={{ fill: '#8A8A8A', fontSize: 11 }} axisLine={false} tickLine={false} dy={10} interval={0} angle={-15} textAnchor="end" height={60} />
                                    <YAxis tick={{ fill: '#8A8A8A', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} />
                                    <Tooltip contentStyle={tooltipStyle} cursor={{ fill: '#FAFAF9' }} />
                                    <Bar dataKey="saves" fill="#8B7355" radius={[4, 4, 0, 0]} maxBarSize={50} />
                                </BarChart>
                            </ResponsiveContainer>
                        )}
                    </div>
                </div>
            </div>

            {/* Charts Row 2 */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* 3. Bar Chart: Offers Usage (Stacked) */}
                <div className="bg-white border border-[#E8E4DF] p-6 shadow-sm rounded-sm">
                    <h3 className="text-sm font-medium text-[#0A0A0A] mb-1">Offers Performance</h3>
                    <p className="text-xs text-[#8A8A8A] mb-6 font-light">Coupon codes claimed vs available uses</p>
                    <div className="h-[300px] w-full">
                        {isLoading ? <div className="h-full flex items-center justify-center text-[#8A8A8A] text-sm">Loading...</div> : (
                            <ResponsiveContainer width="100%" height="100%">
                                <BarChart data={charts.offersPerformance} margin={{ top: 5, right: 20, bottom: 5, left: -20 }}>
                                    <CartesianGrid stroke="#f5f5f5" strokeDasharray="3 3" vertical={false} />
                                    <XAxis dataKey="name" tick={{ fill: '#8A8A8A', fontSize: 11 }} axisLine={false} tickLine={false} dy={10} />
                                    <YAxis tick={{ fill: '#8A8A8A', fontSize: 11 }} axisLine={false} tickLine={false} allowDecimals={false} />
                                    <Tooltip contentStyle={tooltipStyle} cursor={{ fill: '#FAFAF9' }} />
                                    <Legend iconType="circle" wrapperStyle={{ fontSize: '12px', paddingTop: '10px' }} />
                                    <Bar dataKey="used" stackId="a" fill="#5C8A6A" name="Claimed" maxBarSize={40} />
                                    <Bar dataKey="remaining" stackId="a" fill="#E8E4DF" name="Remaining" radius={[4, 4, 0, 0]} maxBarSize={40} />
                                </BarChart>
                            </ResponsiveContainer>
                        )}
                    </div>
                </div>

                {/* 4. Pie Chart: Style Hub Color Preferences */}
                <div className="bg-white border border-[#E8E4DF] p-6 shadow-sm rounded-sm">
                    <h3 className="text-sm font-medium text-[#0A0A0A] mb-1">Style Hub Preferences</h3>
                    <p className="text-xs text-[#8A8A8A] mb-6 font-light">Most selected colors by users building outfits</p>
                    <div className="h-[300px] w-full flex items-center justify-center">
                        {isLoading ? <div className="h-full flex items-center justify-center text-[#8A8A8A] text-sm">Loading...</div> : charts.styleHubColors.length === 0 || (charts.styleHubColors.length === 1 && charts.styleHubColors[0].count === 0) ? (
                            <div className="text-sm text-[#8A8A8A]">No style worlds formulated yet.</div>
                        ) : (
                            <ResponsiveContainer width="100%" height="100%">
                                <PieChart>
                                    <Pie
                                        data={charts.styleHubColors}
                                        cx="50%"
                                        cy="50%"
                                        innerRadius={60}
                                        outerRadius={90}
                                        paddingAngle={5}
                                        dataKey="count"
                                        nameKey="color"
                                    >
                                        {charts.styleHubColors.map((entry, index) => (
                                            <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                                        ))}
                                    </Pie>
                                    <Tooltip contentStyle={tooltipStyle} />
                                    <Legend layout="vertical" verticalAlign="middle" align="right" iconType="circle" wrapperStyle={{ fontSize: '12px' }} />
                                </PieChart>
                            </ResponsiveContainer>
                        )}
                    </div>
                </div>
            </div>

            <div className="bg-[#FAFAF9] border border-[#E8E4DF] p-8 mt-10 text-center rounded-sm">
                <p className="text-sm text-[#4A4A4A] font-light">Analytics dashboard refreshes automatically. Connecting directly to Supabase PostgREST endpoints.</p>
            </div>
        </div>
    );
}
